name: Build-Rachel
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p build
          docker build --build-arg TARGET=rachel -t retro-go:latest .
          docker create --name temp retro-go:latest
          docker cp temp:/app/. build/
          docker rm temp
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Rachel_Build
          path: build/
