name: Build Rachel
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Extract
        run: |
          mkdir -p build
          docker build --build-arg TARGET=rachel -t retro-go:latest .
          docker create --name temp retro-go:latest
          docker cp temp:/app/. build/
          docker rm temp
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Rachel_Build
          path: build/

            


    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: build/*

